apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zxwz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zxwz
    app.kubernetes.io/part-of: ci1t-830-0027-app
  name: devfile-sample-zxwz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zxwz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zxwz
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0027-tenant/ci1t-830-0027-app/devfile-sample-zxwz@sha256:d6f74a8a22b7532816977211fe099d512097fdb648c12d6418ae584a8d8ab960
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
