apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zxwz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0027-tenant/ci1t-830-0027-app/devfile-sample-zxwz@sha256:d6f74a8a22b7532816977211fe099d512097fdb648c12d6418ae584a8d8ab960
        name: my-nodejs
        resources: {}
status: {}
